version: "3.3"
services:
  app-ski:
    build:
      context: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/stationSki?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
      - spring.jpa.hibernate.ddl-auto=update
    ports:
      - "8089:8089"
    image: "slimzouari560/gestion-station-ski"
    depends_on:
      - mysqldb

  mysqldb:
    image: "mysql:5.7"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=stationSki
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

volumes:
  db: